global:
  network: ghostnet
  protocol: "PtTallinn"

node:
  enabled: true
  image:
    tag: "octez-v24.2"
  storage:
    size: 1Gi
    storageClass: ""
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

baker:
  enabled: false

dal:
  enabled: false

snapshot:
  enabled: false
