---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "falkordb.fullname" . }}
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: falkordb
      protocol: TCP
      name: falkordb
  selector:
    {{- include "falkordb.selectorLabels" . | nindent 4 }}
