---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "falkordb.fullname" . }}
  labels:
    {{- include "falkordb.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "falkordb.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "falkordb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "falkordb.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: falkordb
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: falkordb
              containerPort: 6379
              protocol: TCP
          {{- if .Values.auth.enabled }}
          args:
            - --requirepass
            - $(FALKORDB_PASSWORD)
          env:
            - name: FALKORDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "falkordb.secretName" . }}
                  key: password
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.storage.size }}
          volumeMounts:
            - name: data
              mountPath: /data
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.storage.size }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.storage.accessMode }}
        {{- if .Values.storage.className }}
        storageClassName: {{ .Values.storage.className | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
  {{- end }}
