{{- if and .Values.baker.enabled .Values.baker.metrics.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-octez.bakerFullname" . }}
  labels:
    {{- include "tezos-octez.labels" . | nindent 4 }}
    app.kubernetes.io/component: baker
spec:
  type: ClusterIP
  selector:
    {{- include "tezos-octez.bakerSelectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.baker.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
