{{- if not .Values.signatory.auth.existingSecret -}}
{{- $sigUrl := (include "tezos-octez.signatoryUrl" .) | trimSuffix "/" -}}
{{- $keys := dict -}}
{{- if and .Values.baker.enabled .Values.baker.bakerKey -}}
{{-   $_ := set $keys .Values.baker.bakerKeyAlias .Values.baker.bakerKey -}}
{{- end -}}
{{- if .Values.baker.consensusKey -}}
{{-   $_ := set $keys "consensus_key" .Values.baker.consensusKey -}}
{{- end -}}
{{- if .Values.baker.companionKey -}}
{{-   $_ := set $keys "companion_key" .Values.baker.companionKey -}}
{{- end -}}
{{- $dalProfiles := concat (.Values.dal.attesterProfiles | default list) (.Values.dal.operatorProfiles | default list) -}}
{{- range $i, $addr := $dalProfiles -}}
{{-   if not (has $addr (values $keys)) -}}
{{-     $_ := set $keys (printf "profile-%d" $i) $addr -}}
{{-   end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tezos-octez.fullname" . }}-client-keys
  labels:
    {{- include "tezos-octez.labels" . | nindent 4 }}
stringData:
  secret_keys: |
    [
    {{- range $i, $alias := keys $keys | sortAlpha }}
      {"name": "{{ $alias }}", "value": "{{ if $.Values.baker.bakerSecretKey }}unencrypted:{{ $.Values.baker.bakerSecretKey }}{{ else }}{{ $sigUrl }}/{{ index $keys $alias }}{{ end }}"}
      {{- if not (eq $i (sub (len (keys $keys | sortAlpha)) 1)) }},{{ end }}
    {{- end }}
    {{- if and (gt (len (keys $keys)) 0) .Values.signatory.auth.secretKey }},{{ end }}
    {{- if .Values.signatory.auth.secretKey }}
      {"name": "signatory_auth", "value": "unencrypted:{{ .Values.signatory.auth.secretKey }}"}
    {{- end }}
    ]

  public_key_hashs: |
    [
    {{- range $i, $alias := keys $keys | sortAlpha }}
      {"name": "{{ $alias }}", "value": "{{ index $keys $alias }}"}
      {{- if not (eq $i (sub (len (keys $keys | sortAlpha)) 1)) }},{{ end }}
    {{- end }}
    {{- if and (gt (len (keys $keys)) 0) .Values.signatory.auth.publicKeyHash }},{{ end }}
    {{- if .Values.signatory.auth.publicKeyHash }}
      {"name": "signatory_auth", "value": "{{ .Values.signatory.auth.publicKeyHash }}"}
    {{- end }}
    ]

  public_keys: |
    [
    {{- $sep := "" }}
    {{- if .Values.baker.bakerPublicKey }}
      {"name": "{{ .Values.baker.bakerKeyAlias }}", "value": {"locator": "{{ if .Values.baker.bakerSecretKey }}unencrypted:{{ .Values.baker.bakerSecretKey }}{{ else }}{{ $sigUrl }}/{{ .Values.baker.bakerKey }}{{ end }}", "key": "{{ .Values.baker.bakerPublicKey }}"}}
      {{- $sep = "," }}
    {{- end }}
    {{- if .Values.baker.consensusPublicKey }}{{ $sep }}
      {"name": "consensus_key", "value": {"locator": "{{ $sigUrl }}/{{ .Values.baker.consensusKey }}", "key": "{{ .Values.baker.consensusPublicKey }}"}}
      {{- $sep = "," }}
    {{- end }}
    {{- if .Values.baker.companionPublicKey }}{{ $sep }}
      {"name": "companion_key", "value": {"locator": "{{ $sigUrl }}/{{ .Values.baker.companionKey }}", "key": "{{ .Values.baker.companionPublicKey }}"}}
      {{- $sep = "," }}
    {{- end }}
    {{- if .Values.signatory.auth.publicKey }}{{ $sep }}
      {"name": "signatory_auth", "value": {"locator": "unencrypted:{{ .Values.signatory.auth.secretKey }}", "key": "{{ .Values.signatory.auth.publicKey }}"}}
    {{- end }}
    ]
{{- end }}
