{{- if and (not .Values.existingSecret) .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gomodel.fullname" . }}
  labels:
    {{- include "gomodel.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
