apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "heimdall-bot.fullname" . }}
  labels:
    {{- include "heimdall-bot.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.gsaEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ . }}
  {{- end }}
