apiVersion: v1
kind: Service
metadata:
  name: {{ include "tezos-baker-tail.fullname" . }}
  labels:
    {{- include "tezos-baker-tail.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tezos-baker-tail.selectorLabels" . | nindent 4 }}
