{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tezos-baker-tail.serviceAccountName" . }}
  labels:
    {{- include "tezos-baker-tail.labels" . | nindent 4 }}
  {{- with merge (.Values.serviceAccount.annotations | default dict) (.Values.commonAnnotations | default dict) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
