{{- if not .Values.objectStorage.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "juicefs.fullname" . }}-object-storage
  labels:
    {{- include "juicefs.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  access-key: {{ required "juicefs: objectStorage.accessKey is required when objectStorage.existingSecret is empty" .Values.objectStorage.accessKey | quote }}
  secret-key: {{ required "juicefs: objectStorage.secretKey is required when objectStorage.existingSecret is empty" .Values.objectStorage.secretKey | quote }}
{{- end }}
{{- if not .Values.gatewayAuth.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "juicefs.fullname" . }}-gateway-auth
  labels:
    {{- include "juicefs.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  access-key: {{ required "juicefs: gatewayAuth.accessKey is required when gatewayAuth.existingSecret is empty" .Values.gatewayAuth.accessKey | quote }}
  secret-key: {{ required "juicefs: gatewayAuth.secretKey is required when gatewayAuth.existingSecret is empty" .Values.gatewayAuth.secretKey | quote }}
{{- end }}
