{{- $renderAiKey := and .Values.ai.enabled .Values.ai.openai.apiKey (not .Values.ai.openai.existingSecret) -}}
{{- $renderSecretData := and (not .Values.existingSecret) .Values.secretData -}}
{{- if or $renderAiKey $renderSecretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chartdb.fullname" . }}
  labels:
    {{- include "chartdb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- if $renderAiKey }}
  OPENAI_API_KEY: {{ .Values.ai.openai.apiKey | quote }}
  {{- end }}
  {{- if $renderSecretData }}
  {{- range $key, $value := .Values.secretData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
