{{- if empty .Values.signatory.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "signatory.fullname" . }}-keys
  labels:
    {{- include "signatory.labels" . | nindent 4 }}
type: Opaque
data:
  keys.json: {{ toJson .Values.signatory.keys | b64enc }}
{{- end }}
