apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dns-exporter.fullname" . }}
  labels:
    {{- include "dns-exporter.labels" . | nindent 4 }}
data:
  dns_exporter.yml: |
{{ .Values.config | toYaml | indent 6 }}
